### ISSUE TITLE
Someone make better installation instruction

### ISSUE THREAD

**Issue by essoojay** [net-byte/vtun#22]
Can someone who got this running make a better installation wiki, If there is the need for caddy for websocket etc. As the instruction is not ordinary users friendly.
This woukd be appreciated. 

Thanks all..

**Comment by ttyridal** [comment]
Hi,

I honestly don't think this projects audience is "ordinary users" 🤓    

Where did it fail on you?   There are definitively a few quirks, but I got this working with the android app ([net-byte/vTunnel](https://github.com/net-byte/vTunnel)) and following the readme [here](https://github.com/net-byte/vtun#server-on-linux) for the server side.

You don't need caddy, but you do need a server somewhere, with a public ip-address.

To be specific, I used `./vtun-linux-amd64 -S -k 123456 -p ws -l :3001 -path /freedom/`  because I have a reverse proxy running on port 443 that takes care of TLS.

**Comment by malikshi** [comment]
> To be specific, I used `./vtun-linux-amd64 -S -k 123456 -p ws -l :3001 -path /freedom/` because I have a reverse proxy running on port 443 that takes care of TLS.

Care to share nginx config?

**Comment by ttyridal** [comment]
@malikshi 

```
location /freedom/ { 
            proxy_pass http://x.y.z.w:1088/freedom/;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;        
            proxy_set_header Connection $http_connection;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout  36000s;
}
```
should do the business :)

**Comment by malikshi** [comment]
> I honestly don't think this projects audience is "ordinary users" 🤓

I did try with how nginx reverse work but seem failed in early build. It's been while and I saw new release to try luck again.

**Comment by malikshi** [comment]
> @malikshi
> 
> ```
> location /freedom/ { 
>             proxy_pass http://x.y.z.w:1088/freedom/;
>             proxy_buffering off;
>             proxy_http_version 1.1;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header Upgrade $http_upgrade;        
>             proxy_set_header Connection $http_connection;
>             proxy_set_header Host $host;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_read_timeout  36000s;
> }
> ```
> 
> should do the business :)

Thx you sir I will tests it later
